### ISSUE TITLE
save path issue with v0.0.6-alpha

### ISSUE THREAD

**Issue by AlbertFnWesker** [Namsku/REviewer#27]
The newest version with re2 seems to work fine so far but there is an issue where the save path doesn't save, every time i reopen the REviewer i have to refind the save path.

**Comment by Namsku** [comment]
Interesting, never had this bug, will try to reproduce it

**Comment by AlbertFnWesker** [comment]
ok so it turns out i did something in the wrong order, if you press the cog first it will show the save paths as empty, but if you go to game selection first and pick the game then the save paths fill in with the correct save paths. so not a big deal, i just did things in the wrong order.

**Comment by Namsku** [comment]
@AlbertFnWesker is this better now ? with build v0.0.7-alpha

**Comment by AlbertFnWesker** [comment]
yep just tried it, all re 1-3 save paths are saving now, issue fixed

**Comment by Namsku** [comment]
Awesome
