### ISSUE TITLE
REviewer and Win 7 pro 32 bit

### ISSUE THREAD

**Issue by otamega72** [Namsku/REviewer#29]
Does REviewer not support Windows 7 Pro and/or 32-bit?

**Comment by Namsku** [comment]
Hmm It's using .NET 7+
Windows 7 seems to be .NET 6 Max

I would have to refactored the whole code for retro compatibility, let's see after i have done all my stuff if I'm able to do something, but so far, i feel it's a lot amount of work.

**Comment by Namsku** [comment]
.NET 6.0 implemented in upcoming v0.0.7-alpha

**Comment by otamega72** [comment]
![Capture](https://github.com/Namsku/REviewer/assets/120957601/2277012a-137e-4e73-b628-d73f5fbdce16)

**Comment by Namsku** [comment]
What the heck, okay i need to look deeper

**Comment by Namsku** [comment]
0.0.8 is fixing this
