### ISSUE TITLE
not all enemies showing up on enemy tracker - re2

### ISSUE THREAD

**Issue by AlbertFnWesker** [Namsku/REviewer#34]
tried the newest version of REviewer, i noticed twice not all enemies showed up on the tracker. 2 mr X in the sewer but only 1 got tracked, and also on the way to the first boss room there was a birkin down there but the tracker didnt track it. 
![chrome_R2IHJdu4x2](https://github.com/Namsku/REviewer/assets/121378553/3f970268-f2a8-42f0-83d8-0d35ee141cf9)
![chrome_aqe9bQO3cw](https://github.com/Namsku/REviewer/assets/121378553/c3ec37db-2201-4cd2-a8ac-2763eea95212)

**Comment by Namsku** [comment]
I might put a too strict rule for removing enemy, i'll watch your stream and reproduce your biorand seed

**Comment by AlbertFnWesker** [comment]
if its any help this was the seed R821-YPCJ-XN24100TY3G0904G13X80W1K496QUNLW1G7TLG5QYVZZZZZ6E6Y40H00ZZ

**Comment by Namsku** [comment]
Rollback on the future 0.0.9-alpha, i will have to re-implement it

**Comment by Namsku** [comment]
Fixed in 0.0.10
